// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFeed(arg1, arg2) {
  return window['go']['main']['App']['CreateFeed'](arg1, arg2);
}

export function FetchRemoteArticles(arg1) {
  return window['go']['main']['App']['FetchRemoteArticles'](arg1);
}

export function GetFeedById(arg1) {
  return window['go']['main']['App']['GetFeedById'](arg1);
}

export function GetStoredArticles(arg1) {
  return window['go']['main']['App']['GetStoredArticles'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListFeeds() {
  return window['go']['main']['App']['ListFeeds']();
}
