// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {feed} from '../models';

export function CreateFeed(arg1:string,arg2:string):Promise<feed.Feed>;

export function Greet(arg1:string):Promise<string>;
