// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {feed} from '../models';

export function CreateFeed(arg1:string,arg2:string):Promise<feed.Feed>;

export function FetchRemoteArticles(arg1:number):Promise<Array<feed.FeedArticleListItemDto>>;

export function GetFeedById(arg1:number):Promise<feed.Feed>;

export function GetStoredArticles(arg1:number):Promise<Array<feed.FeedArticleListItemDto>>;

export function Greet(arg1:string):Promise<string>;

export function ListFeeds():Promise<Array<feed.Feed>>;

export function MarkArticleAsRead(arg1:string):Promise<void>;
